baseURL = "https://hsinjungwu.github.io/talks" # please update this to your actual URL
languageCode = "en-us"
title = "廢文集"
theme = "hugo-xmin"
disqusShortname = ""
ignoreFiles = []
footnotereturnlinkcontents = "↩"

[menu]
[[menu.main]]
name = "Home"
url = ""
weight = 1

[[menu.main]]
name = "About"
url = "about/"
weight = 2

[[menu.main]]
name = "Categories"
url = "categories/"
weight = 3

[[menu.main]]
name = "Tags"
url = "tags/"
weight = 4

[params]
footer = "A blog built with [Hugo](https://gohugo.io/) and the [hugo-xmin](https://github.com/yihui/hugo-xmin/) theme <br> &copy; 我 2000 -- {Year}"

[markup]
[markup.highlight]
codeFences = false

[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true
